"""Add SavedPlan table

Revision ID: fdf3f3f61a89
Revises: a08abcac0f67
Create Date: 2025-09-26 16:02:31.856328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf3f3f61a89'
down_revision: Union[str, None] = 'a08abcac0f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
